### PR TITLE
Add hebrew language support

### PR DESCRIPTION
**Pull request by baget**
Adding Hebrew localization

### CODE REVIEW

**Comment by AitorDB** [comment]
Thanks for the PR! Would you mind to add some of the new texts? Here's an updated example in English. It will be awesome if you could also fix the indentation (2 spaces) and the line at the end

```
{
  "Azimuth": "Azimuth",
  "Dawn": "Dawn",
  "Dusk": "Dusk",
  "Elevation": "Elevation",
  "Noon": "Solar noon",
  "Sunrise": "Sunrise",
  "Sunset": "Sunset",
  "errors": {
    "SunIntegrationNotFound": "Sun integration not found"
  }
}
```

**Comment by baget** [comment]
> Thanks for the PR! Would you mind to add some of the new texts? Here's an updated example in English. It will be awesome if you could also fix the indentation (2 spaces) and the line at the end
> 
> ```
> {
>   "Azimuth": "Azimuth",
>   "Dawn": "Dawn",
>   "Dusk": "Dusk",
>   "Elevation": "Elevation",
>   "Noon": "Solar noon",
>   "Sunrise": "Sunrise",
>   "Sunset": "Sunset",
>   "errors": {
>     "SunIntegrationNotFound": "Sun integration not found"
>   }
> }
> ```

Sure, no problem, WIP

**Comment by idoaflalo** [comment]
Looks pretty good!

**Comment by AitorDB** [comment]
Sorry for asking for more changes, but the indentation is not 2 spaces and there's an issue with the last line, could you fix that?

**Comment by baget** [comment]
> Sorry for asking for more changes, but the indentation is not 2 spaces and there's an issue with the last line, could you fix that?

so what is the indentation ??

**Comment by baget** [comment]
I hope it is ok now.

**Review by idoaflalo — APPROVED** [review]
Looks ok to me :)

**Pull request merged**
